### ISSUE TITLE
Can't build PulseView

### ISSUE THREAD

**Issue by tengelmeier** [rene-dev/homebrew-sigrok#5]
It looks like the --HEAD version of PulseView depends on the C++ bindings which are not build by default 

      # CMakeList.txt, line 61:
      list(APPEND PKGDEPS libsigrokxx>=0.3.0)

and my simplistic approach to get it done fails: 

      brew install autoconf-archive
      brew install glibmm
      brew install --HEAD --with-libserialport --with-bindings_cxx -vvv libsigrok

How can I update the formula to include the C++ bindings?

....

HEAD is now at 15eea61 Fix compile error on FreeBSD
==> Checking out branch master
git checkout-index -a -f --prefix=/private/tmp/libsigrok-6k9KVc/
==> Patching
==> ./autogen.sh
Generating build system...
/usr/bin/sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
--- Warning: AX_CXX_COMPILE_STDCXX_11 macro not found.
--- You won't be able to build the language bindings!
--- More info: http://sigrok.org/wiki/Building#FAQ
configure.ac:39: installing 'autostuff/ar-lib'

**Comment by rene-dev** [comment]
this is related to http://sigrok.org/bugzilla/show_bug.cgi?id=516
and here is a patch: http://sourceforge.net/p/sigrok/mailman/message/33206533/

**Comment by rene-dev** [comment]
libsigrokxx bindings are not being built, but pulseview does not link due to this issue: http://sigrok.org/bugzilla/show_bug.cgi?id=534

**Comment by rene-dev** [comment]
Bug 534 is now closed. It requires rebuilding libsigrok.
